### ISSUE TITLE
Remote data provenance

### ISSUE THREAD

**Issue by brandomr** [jataware/domain-model-examiner#10]
For data that comes from the web, try to identify provenance information. We could potentially leverage the Wikipedia API to gather a high level description of the source. For example, the [FAO Wikipedia page](https://en.wikipedia.org/wiki/Fao) has rich information about that organization.

Additionally, we should consider grabbing column headers from all data files and inputs when possible. This could be organized as below (for example):

```
    usda.gov:
        - provenance: "DESCRIPTION OF USDA (from wiki?) HERE" 
        - files:
            - psd_grains_pulses_csv:
                url: https://apps.fas.usda.gov/psdonline/downloads/psd_grains_pulses_csv.zip
                columns: ["price", "yield"]
```
